function Hammer(e,d,w){var k,h;function z(a){a=a||window.event;if(D){for(var b=[],c=0<a.touches.length?a.touches:a.changedTouches,d=0,f=c.length;d<f;d++)a=c[d],b.push({x:a.pageX,y:a.pageY});return b}b=document;c=b.body;return[{x:a.pageX||a.clientX+(b&&b.scrollLeft||c&&c.scrollLeft||0)-(b&&b.clientLeft||c&&b.clientLeft||0),y:a.pageY||a.clientY+(b&&b.scrollTop||c&&c.scrollTop||0)-(b&&b.clientTop||c&&b.clientTop||0)}]}function E(a,b){if(2==a.length&&2==b.length){var c,d;c=a[0].x-a[1].x;d=a[0].y-a[1].y;
var f=Math.sqrt(c*c+d*d);c=b[0].x-b[1].x;d=b[0].y-b[1].y;return Math.sqrt(c*c+d*d)/f}return 0}function F(a,b){if(2==a.length&&2==b.length){var c,d;c=a[0].x-a[1].x;d=a[0].y-a[1].y;var f=180*Math.atan2(d,c)/Math.PI;c=b[0].x-b[1].x;d=b[0].y-b[1].y;return 180*Math.atan2(d,c)/Math.PI-f}return 0}function i(a,b){b.touches=z(b.originalEvent);b.type=a;"[object Function]"==Object.prototype.toString.call(s["on"+a])&&s["on"+a].call(s,b)}function t(a){a=a||window.event;a.preventDefault?(a.preventDefault(),a.stopPropagation()):
(a.returnValue=!1,a.cancelBubble=!0)}function A(a){switch(a.type){case "mousedown":case "touchstart":c.start=z(a);x=(new Date).getTime();q=!0;G=a;var b=e.getBoundingClientRect();k=b.top+(window.pageYOffset||e.scrollTop||document.body.scrollTop)-(e.clientTop||document.body.clientTop||0);h=b.left+(window.pageXOffset||e.scrollLeft||document.body.scrollLeft)-(e.clientLeft||document.body.clientLeft||0);y=!0;u.hold(a);d.prevent_default&&t(a);break;case "mousemove":case "touchmove":if(!y)return!1;c.move=
z(a);u.transform(a)||u.drag(a);break;case "mouseup":case "mouseout":case "touchcancel":case "touchend":if(!y||"transform"!=f&&a.touches&&0<a.touches.length)return!1;y=!1;b="drag"==f;u.swipe(a);b?i("dragend",{originalEvent:a,direction:o,distance:j,angle:m}):"transform"==f?i("transformend",{originalEvent:a,position:c.center,scale:E(c.start,c.move),rotation:F(c.start,c.move)}):u.tap(G);H=f;i("release",{originalEvent:a,gesture:f});c={};q=!1;m=j=0;f=null}}function B(a,b,c){for(var b=b.split(" "),d=0,f=
b.length;d<f;d++)a.addEventListener?a.addEventListener(b[d],c,!1):document.attachEvent&&a.attachEvent("on"+b[d],c)}var s=this;var p={prevent_default:!1,css_hacks:!0,swipe:!0,swipe_time:200,swipe_min_distance:20,drag:!0,drag_vertical:!0,drag_horizontal:!0,drag_min_distance:20,transform:!0,scale_treshold:0.1,rotation_treshold:15,tap:!0,tap_double:!0,tap_max_interval:300,tap_max_distance:10,tap_double_distance:20,hold:!0,hold_timeout:500},r=d,n={};if(r){for(var l in p)n[l]=l in r?r[l]:p[l];d=n}else d=
p;if(d.css_hacks){p=["webkit","moz","ms","o",""];r={userSelect:"none",touchCallout:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"};n="";for(l=0;l<p.length;l++)for(var I in r)n=I,p[l]&&(n=p[l]+n.substring(0,1).toUpperCase()+n.substring(1)),e.style[n]=r[I]}var j=0,m=0,o=0,c={},q=!1,f=null,H=null,x=null,v={x:0,y:0},C=null,J=null;h=k=void 0;var y=!1,G,D="ontouchstart"in window;this.option=function(a,b){b!=w&&(d[a]=b);return d[a]};this.getDirectionFromAngle=function(a){var a={down:45<=a&&135>
a,left:135<=a||-135>=a,up:-45>a&&-135<a,right:-45<=a&&45>=a},b,c;for(c in a)if(a[c]){b=c;break}return b};var u={hold:function(a){d.hold&&(f="hold",clearTimeout(J),J=setTimeout(function(){"hold"==f&&i("hold",{originalEvent:a,position:c.start})},d.hold_timeout))},swipe:function(a){if(c.move){var b=c.move[0].x-c.start[0].x,g=c.move[0].y-c.start[0].y;j=Math.sqrt(b*b+g*g);var e=(new Date).getTime()-x;d.swipe&&(d.swipe_time>e&&j>d.swipe_min_distance)&&(m=180*Math.atan2(c.move[0].y-c.start[0].y,c.move[0].x-
c.start[0].x)/Math.PI,o=s.getDirectionFromAngle(m),f="swipe",i("swipe",{originalEvent:a,position:{x:c.move[0].x-h,y:c.move[0].y-k},direction:o,distance:j,distanceX:b,distanceY:g,angle:m}))}},drag:function(a){var b=c.move[0].x-c.start[0].x,g=c.move[0].y-c.start[0].y;j=Math.sqrt(b*b+g*g);if(d.drag&&j>d.drag_min_distance||"drag"==f){m=180*Math.atan2(c.move[0].y-c.start[0].y,c.move[0].x-c.start[0].x)/Math.PI;o=s.getDirectionFromAngle(m);var e="up"==o||"down"==o;(e&&!d.drag_vertical||!e&&!d.drag_horizontal)&&
j>d.drag_min_distance||(f="drag",b={originalEvent:a,position:{x:c.move[0].x-h,y:c.move[0].y-k},direction:o,distance:j,distanceX:b,distanceY:g,angle:m},q&&(i("dragstart",b),q=!1),i("drag",b),t(a))}},transform:function(a){if(d.transform){if(2!=(a.touches?a.touches.length:1))return!1;var b=F(c.start,c.move),g=E(c.start,c.move);if("drag"!=f&&("transform"==f||Math.abs(1-g)>d.scale_treshold||Math.abs(b)>d.rotation_treshold))return f="transform",c.center={x:(c.move[0].x+c.move[1].x)/2-h,y:(c.move[0].y+c.move[1].y)/
2-k},b={originalEvent:a,position:c.center,scale:g,rotation:b},q&&(i("transformstart",b),q=!1),i("transform",b),t(a),!0}return!1},tap:function(a){var b=(new Date).getTime(),g=b-x;if(!d.hold||d.hold&&d.hold_timeout>g){if(v&&d.tap_double&&"tap"==H&&x-C<d.tap_max_interval)var g=Math.abs(v[0].x-c.start[0].x),e=Math.abs(v[0].y-c.start[0].y),g=v&&c.start&&Math.max(g,e)<d.tap_double_distance;else g=!1;g?(f="double_tap",C=null,i("doubletap",{originalEvent:a,position:c.start}),t(a)):(g=c.move?Math.abs(c.move[0].x-
c.start[0].x):0,e=c.move?Math.abs(c.move[0].y-c.start[0].y):0,j=Math.max(g,e),j<d.tap_max_distance&&(f="tap",C=b,v=c.start,d.tap&&(i("tap",{originalEvent:a,position:c.start}),t(a))))}}};D?B(e,"touchstart touchmove touchend touchcancel",A):(B(e,"mouseup mousedown mousemove",A),B(e,"mouseout",function(a){var b;a:if(b=a.relatedTarget,!b&&(window.event&&window.event.toElement)&&(b=window.event.toElement),e===b)b=!0;else{if(b)for(b=b.parentNode;null!==b;){if(b===e){b=!0;break a}b=b.parentNode}b=!1}b||
A(a)}))}jQuery.fn.hammer=function(e){return this.each(function(){var d=new Hammer(this,e),w=jQuery(this);w.data("hammer",d);for(var k="hold tap doubletap transformstart transform transformend dragstart drag dragend swipe release".split(" "),h=0;h<k.length;h++)d["on"+k[h]]=function(d,e){return function(h){d.trigger(jQuery.Event(e,h))}}(w,k[h])})};